### ISSUE TITLE
Request for the omg crate name

### ISSUE THREAD

**Issue by supleed2** [maxjacobson/omg#1]
Hi,

I'm learning Rust and was checking which crate names are available for a project I'm starting, I saw your note on crates.io and I'm wondering if I could take the omg crate?

I'm planning to use it for a CLI app to communicate with the omg.lol API

**Comment by maxjacobson** [comment]
Hi @supleed2! Sure, happy to hand it over. I'm not sure how... I guess I can add you as a collaborator on the crate and then you can remove me. Does that sound right?

**Comment by supleed2** [comment]
I think that's how it works, yeah!

**Comment by maxjacobson** [comment]
@supleed2 what's your crates.io username?

**Comment by maxjacobson** [comment]
<img width="994" alt="Screenshot 2023-04-14 at 13 48 39" src="https://user-images.githubusercontent.com/1421211/232119689-ad2dd26c-4221-4af5-a1f5-26ca93bb0510.png">

**Comment by supleed2** [comment]
Ah yep, https://crates.io/users/supleed2, I think logging in to crates.io is still limited to via GitHub

**Comment by maxjacobson** [comment]
@supleed2 alright! invite sent

**Comment by supleed2** [comment]
Thank you ❤️ it seems to have worked, though I'm still confused where all the downloads are coming from considering the old crate was just a single test. (Almost 60 in the last 3 months?)

**Comment by maxjacobson** [comment]
> Thank you ❤️ it seems to have worked, though I'm still confused where all the downloads are coming from considering the old crate was just a single test. (Almost 60 in the last 3 months?)

🤷🏻 I suspect there are some third-party bots that auto-download everything for analysis or archiving or something. Wouldn't read too much into it.
